<a href="https://colab.research.google.com/github/darlaabril/Taller-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy




Numpy y sus aplicaciones

In [ ]:
#Una diferencia importante entre NumPy y List es que NumPy es más rapida de leer
#Algunas aplicaciones de NumPy son las Funciones matemáticas y manejo de arrays

Instalar Numpy


In [2]:
#No se olviden instalar Numpy antes de usarlo
#Instalación:
import numpy as np
import sys


Creación de arrays, forma, tamaño y tipo de data

In [ ]:
#Creación de array
a=np.array([2,4,8], dtype="int")
print(a)

[2 4 8]


In [ ]:
b=np.array([[3,6,9],[1,3,5]])
print(b)

[[3 6 9]
 [1 3 5]]


In [ ]:
#Ver la dimensión
b.ndim

2

In [ ]:
#Ver la forma
b.shape

(2, 3)

In [ ]:
#Ver el tipo de data, int16 para valores no tan grandes
#Es eficiente especificarlo
a.dtype

dtype('int64')

In [ ]:
#Ver el tamaño (bytes)
a.itemsize

8

Acceder/cambiar elementos específicos, filas, columnas, etc

In [5]:
a=np.array ([ [1,3,5,7,9,11,13 ],[ 2,4,6,8,10,12,14]])
print(a)

[[ 1  3  5  7  9 11 13]
 [ 2  4  6  8 10 12 14]]


In [ ]:
 #Elemento especifico [fila, columna]
 a[1,5]

12

In [ ]:
#Fila
a[ 0,:]

array([ 1,  3,  5,  7,  9, 11, 13])

In [ ]:
#Columna
a[:,2 ]

array([5, 6])

In [ ]:
#Cambiar data
a[ 1,5]=40
print(a)

[[ 1  3  5  7  9 11 13]
 [ 2  4  6  8 10 40 14]]


In [ ]:
b=np.array([[[ 2,4], [ 6,8]], [ [10,12 ],[ 14,16]]])
print(b)

[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


In [ ]:
#[matriz, fila, columna]
b[0,1,1]

8

In [ ]:
#Obtener un elemento específico fuera del array
#en el siguiente ej no especificamos cual de las 2 matrices por lo que obtendremos 2 filas
b[:,1,:]

array([[ 6,  8],
       [14, 16]])

In [ ]:
#reemplazo 
b[:,1,:]= [[1,1],[2,2]]
print(b)

[[[ 2  4]
  [ 1  1]]

 [[10 12]
  [ 2  2]]]


Inicialización

In [ ]:
#Matriz de 0's
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#Matriz de 1's
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
#Matriz de n's
np.full((2,3),13)

array([[13, 13, 13],
       [13, 13, 13]])

In [ ]:
#Matriz con x forma
np.full_like(a,2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [3]:
#Numeros decimales aleatorios
np.random.rand(3,4)

array([[0.69478552, 0.43656425, 0.27858578, 0.48928041],
       [0.45815969, 0.85387559, 0.97358014, 0.9661191 ],
       [0.04789364, 0.65126972, 0.63635707, 0.74659623]])

In [6]:
#Numeros decimales aleatorios como a
np.random.random_sample(a.shape)

array([[0.35160501, 0.05831643, 0.25373617, 0.17967399, 0.55072633,
        0.49271272, 0.41980826],
       [0.40124797, 0.84926965, 0.28229872, 0.23047384, 0.84382844,
        0.45643541, 0.96481504]])

In [ ]:
#Numeros enteros aleatorios (Startvalue, shape)
np.random.randint(1,9,size=(3,3))

array([[1, 8, 4],
       [8, 1, 1],
       [1, 7, 3]])

In [ ]:
#Matriz de identidad
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Repetir un array
arr=np.array([[2,4,6]])
rl=np.repeat(arr,3,axis=0)
print(rl)

[[2 4 6]
 [2 4 6]
 [2 4 6]]


In [ ]:
#Modificar array
x=np.array([2, 4, 6])
y=x
y [0]=40
print(x)

[40  4  6]


Matemática básica

In [ ]:
a=np.array([40, 4,  6])
print(a)

[40  4  6]


In [ ]:
a+2

array([42,  6,  8])

In [ ]:
a-2

array([38,  2,  4])

In [ ]:
a*2

array([80,  8, 12])

In [ ]:
a/2

array([20.,  2.,  3.])

In [ ]:
b=np.array([10,  2,  3])
a+b

array([50,  6,  9])

Reorganizar matrices

In [ ]:
#Apilar vectores: forma vertical
v1=np.array([1,  2,  3])
v2=np.array([4,5,6])
np.vstack([v1,v2])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Apilar vectores: forma horizontal
h1=np.array([1,  2,  3])
h2=np.array([4,5,6])
np.hstack([h1,h2])

array([1, 2, 3, 4, 5, 6])